name: Package Application with Pyinstaller
            
on: push

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.9'
          spec: 'Tools/MasInstaller.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'MasInstaller'
          options: --onefile, --name "MasInstaller", --windowed, 