jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'MasInstaller.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'MasInstaller'
          options: --onefile, --name "MasInstaller", --windowed, 